MIN_NOTE_DURATION = 0.006
MAX_PIECE_DURATION = 18.0
MAX_NOTE_GAP = 0.05
MAX_BR_NOTE_DURATION = 1.2
MIN_BR_NOTE_DURATION = 0.2
BR_ADD_DURATION = 0.3
BR_INTERVAL_DURATION = 3.0
MIN_SILENCE_DURATION = 1.2
VOWEL_MIN_LEN = 0.06

DEFAULT_SINGER = "然糊糊"
DEFAULT_SINGER_ID = 26
DEFAULT_SEED = 23